version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - rm -f /root/.m2/settings.xml
      - cp settings.xml /root/.m2/settings.xml
      - echo Packaging the application
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/vaadiyan-core.jar
  discard-paths: yes